name: metgem
channels:
    - vtraag
    - anaconda
    - conda-forge
    - bioconda
dependencies:
    - pandas>=0.22
    - lxml>=4.0
    - numpy>=1.14
    - pyqt>=5.9
    - pyteomics>=3.4
    - python-igraph>=0.7.1
    - scikit-learn>=0.19
    - scipy>=1.0.0
    - sip>=4.19
    - qtconsole>=4.3
    - matplotlib>=2.2
    - requests>=2.18
    - SQLAlchemy>=1.2
    - pyarrow>=0.9.0
    - pywin32>=223          [win]
    - pluginbase>1.0
    - pyyaml>=3.13
    - pip:
        - py2cytoscape>=0.7.0