name: metgem
channels:
    - conda-forge
    - bioconda
dependencies:
    - setuptools
    - pandas>=0.22
    - lxml>=4.0
    - numpy>=1.14
    - pyside6
    - qt6-main>=6.4.3
    - python-igraph>=0.7.1
    - scikit-learn>=0.19
    - scipy>=1.0.0,<=1.12.0
    - qtconsole-base>=4.3
    - matplotlib-base>=2.2
    - requests>=2.18
    - sqlalchemy>=1.2
    - pyarrow>=0.15.1
    - pluginbase>=1.0
    - pyyaml>=3.13
    - rdkit
    - numexpr>=2.7.0
    - xlrd
    - openpyxl
    - odfpy
    - feedparser
    - mplcursors
    - py2cytoscape>=0.7.0
    - libmetgem>=0.7.0
    - pyside6mn>=0.7.4
    - fa2_modifed>=0.3.5
    - pyemf3>=3.3
    - pyside6qtads>=4.1.0
    - numba>=0.46.0
    - umap-learn>=0.5.0
    - pynndescent>=0.5.0
    - phate>=0.4.5
    - hdbscan>=0.8
    - click>=8.0
    - tornado>=6.1