name: metgem
channels:
    - conda-forge
    - metgem
    - bioconda
dependencies:
    - setuptools<60.0
    - pandas>=0.22
    - lxml>=4.0
    - numpy>=1.14
    - pyside2>=5.12
    - python-igraph>=0.7.1
    - scikit-learn>=0.19
    - scipy>=1.0.0
    - qtconsole-base>=4.3
    - matplotlib-base>=2.2
    - requests>=2.18
    - sqlalchemy>=1.2
    - pyarrow>=0.15.1
    - pluginbase>=1.0
    - pyyaml>=3.13
    - rdkit
    - numexpr>=2.7.0
    - xlrd
    - odfpy
    - feedparser
    - mplcursors
    - py2cytoscape>=0.7.0
    - libmetgem>=0.6.3
    - pyside2mn>=0.6.0
    - forceatlas2>=0.3.6
    - pyemf>=2.1.2alpha
    - pyside2ads>=3.7.2
    - numba>=0.46.0
    - umap-learn>=0.5.0
    - pynndescent>=0.5.0
    - phate>=0.4.5
    - hdbscan>=0.8
    - click>=8.0
    - tornado>=6.1