name: metgem
channels:
    - vtraag
    - anaconda
    - conda-forge
    - bioconda
    - rdkit
dependencies:
    - pip
    - pandas>=0.22
    - lxml>=4.0
    - numpy>=1.14
    - pyqt>=5.9
    - python-igraph>=0.7.1
    - scikit-learn>=0.19
    - scipy>=1.0.0
    - qtconsole>=4.3
    - matplotlib>=2.2
    - requests>=2.18
    - sqlalchemy>=1.2
    - pyarrow>=0.9.0
    - pluginbase>=1.0
    - pyyaml>=3.13
    - rdkit
    - numexpr>=2.7.0
    - xlrd
    - odfpy
    - feedparser
    - mplcursors
    - pip:
        - py2cytoscape>=0.7.0
