name: metgem
channels:
    - conda-forge
    - metgem
    - bioconda
dependencies:
    - pandas>=0.22
    - lxml>=4.0
    - numpy>=1.14, <=1.19.2
    - pyqt>=5.9
    - python-igraph>=0.7.1
    - scikit-learn>=0.19
    - scipy>=1.0.0
    - qtconsole>=4.3
    - matplotlib>=2.2
    - requests>=2.18
    - sqlalchemy>=1.2
    - pyarrow>=0.15.1
    - pluginbase>=1.0
    - pyyaml>=3.13
    - rdkit
    - numexpr>=2.7.0
    - xlrd
    - odfpy
    - feedparser
    - mplcursors
    - py2cytoscape>=0.7.0
    - libmetgem>=0.6.2
    - pyqtnetworkview>=0.5.9
    - forceatlas2>=0.2
    - pyemf>=2.1.2alpha
    - pyqtads>=3.7.2
    - numba>=0.46.0
    - umap-learn>=0.5.0
    - pynndescent>=0.5.0
    - phate>=0.4.5
    - hdbscan>=0.8
    - click>=8.0
