name: metgem
channels:
    - conda-forge
    - metgem
    - bioconda
dependencies:
    - pandas>=0.22
    - lxml>=4.0
    - numpy>=1.14
    - pyqt>=5.9
    - python-igraph>=0.7.1
    - scikit-learn>=0.19
    - scipy>=1.0.0
    - qtconsole>=4.3
    - matplotlib>=2.2
    - requests>=2.18
    - sqlalchemy>=1.2
    - pyarrow>=0.9.0
    - pluginbase>=1.0
    - pyyaml>=3.13
    - rdkit
    - numexpr>=2.7.0
    - xlrd
    - odfpy
    - feedparser
    - mplcursors
    - py2cytoscape>=0.7.0
    - libmetgem>=0.4
    - pyqtnetworkview>=0.5.1
    - forceatlas2>=0.2
    - pyemf>=2.1.2alpha
    - pyqtads>=3.3.0
    - numba>=0.46.0
    - umap-learn>=0.3.10
    - phate>=0.4.5
