name: Nightly

on:
  schedule:
    - cron: "0 2 * * *" # run at 2 AM UTC
  workflow_dispatch:
  repository_dispatch:
    types: nightly-build
    
defaults:
  run:
    shell: bash -l {0}
    
env:
  GITHUB_TOKEN: ${{ github.token }}
  # https://setuptools.pypa.io/en/latest/history.html#breaking-changes
  SETUPTOOLS_USE_DISTUTILS: stdlib

jobs:
  build:
    needs: check-assets
    if: needs.check-assets.outputs.needs-build == 'true'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.9]
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Cache conda
      id: cache
      uses: actions/cache@v2
      env:
        # Increase this value to reset cache if environment.yml has not changed
        CACHE_NUMBER: 2
      with:
        path: |
            ~/conda_pkgs_dir
            ~/conda-env-explicit.txt
        key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment*.yml') }}
    - name: Check Cache
      id: check-cache
      uses: ./.github/actions/get_environment
      with:
        cache-hit: ${{ steps.cache.outputs.cache-hit }}
        python-version: ${{ matrix.python-version }}
    - name: Set up Python
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: metgem
        mamba-version: "*"
        channel-priority: strict
        channels: conda-forge,metgem,bioconda
        python-version: ${{ steps.check-cache.outputs.python-version }}
        environment-file: ${{ steps.check-cache.outputs.environment }}
        use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
    - run: |
        conda info
        conda list
        conda config --show-sources
        conda config --show
    - name: Install Build Dependencies
      uses: ./.github/actions/install_build_dependencies
      with:
        pip-only: ${{ steps.check-cache.outputs.explicit }}
    - name: Fetch tags
      run: git fetch --prune --unshallow # This is important to get version from versioneer
    - name: Build
      id: build
      uses: ./.github/actions/build
    - name: Run Tests
      id: tests
      uses: ./.github/actions/tests
    - name: Upload Tests Artifacts
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: tests
        path: ${{ steps.tests.outputs.log }}
    - name: Deploy Nightly
      uses: WebFreak001/deploy-nightly@v1.1.0
      with:
        upload_url: https://uploads.github.com/repos/${{ github.repository }}/releases/33563969/assets{?name,label}
        release_id: 33563969
        asset_path: metgem_packaging/${{ steps.build.outputs.asset-name }}
        asset_name: ${{ steps.build.outputs.asset-basename }}-$$.${{ steps.build.outputs.asset-ext }}
        asset_content_type: ${{ steps.build.outputs.asset-mimetype }}
        max_releases: 6
        
  # Check that current commit does not have a nightly build asset uploaded yet
  check-assets:
    runs-on: ubuntu-latest
    outputs:
      needs-build: ${{ steps.assets.outputs.needs-build }}
    steps:
      - name: Check existing assets
        id: assets
        run: |
          hash=${{ github.sha }}
          hash=${hash::6}
          names=( $(curl -sL https://api.github.com/repos/${{ github.repository }}/releases/33563969/assets | jq -r '.[].name') )
          needs_build='true'
          if [ "${{ github.event_name }}" == "repository_dispatch" || "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "[WARNING] Nightly workflow triggered manually"
          else
            for name in "${names[@]}"
            do
              basename=${name##*-};
              if [ "${basename%.*}" == "$hash" ]; then
                echo "[WARNING] Commit already built, skipping build"
                needs_build='false'
                break
              fi
            done
          fi
          echo "::set-output name=needs-build::$needs_build"
          
  update-nightly-tag:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Update Nightly tag
        uses: richardsimko/update-tag@v1
        with:
          tag_name: nightly