name: Release

on:
  release:
    types: [ published ]
    branches: [ master ]
    
env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.7]
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }} (Miniconda)
      uses: goanpeca/setup-miniconda@v1
      with:
        auto-update-conda: true
        activate-environment: metgem
        python-version: ${{ matrix.python-version }}
        environment-file: environment.yml
    - name: Conda info
      shell: bash -l {0}
      run: |
        conda info
        conda list
        conda config --show-sources
        conda config --show
    - name: Install build dependencies
      shell: bash -l {0}
      run: conda install invoke pyinstaller
    - name: Test invoke command
      shell: bash -l {0}
      run: inv -l
    - name: Install build dependencies (macOS)
      shell: bash -l {0}
      run: pip install dmgbuild biplist
      if: runner.os == 'macOS'
    - name: Install build dependencies (Windows)
      shell: bash -l {0}
      run: conda install pywin32
      if: runner.os == 'Windows'
    - name: Build
      id: build
      shell: bash -l {0}
      run: |
        python -m invoke packaging.build
        shopt -s extglob
        echo "::set-output name=asset_name::`find packaging -maxdepth 1 \( -name "setup_MetGem*" -or -name "MetGem*.dmg" -or -name "MetGem*.AppImage" \) -printf "%T@ %f\n" | sort -r | cut -d' ' -f2`"
    - name: Check Asset Path
      shell: bash -l {0}
      run: echo "${{ steps.build.outputs.asset_path }}"
    - name: Get Release
      id: get_release
      uses: bruceadams/get-release@v1.2.0
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }} 
        asset_path: packaging/${{ steps.build.outputs.asset_name }}
        asset_name: ${{ steps.build.outputs.asset_name }}
        asset_content_type: application/octet-stream
